### ISSUE TITLE
Failed to mount 'secrets-init-bin' volume

### ISSUE THREAD

**Issue by burningalchemist** [doitintl/kube-secrets-init#21] opened 2021-04-21 10:31 UTC
Hello team,

There is an issue when using `kube-secrets-init` as an admission webhook with the latest version. The initContainer injected in the pod fails with the following error:
```
Error: failed to start container "copy-secrets-init": Error response from daemon:
OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init
caused \"rootfs_linux.go:58:
mounting \\\"/var/lib/kubelet/pods/f3148abf-de2a-4ebd-8288-
90b3afb7f708/volumes/kubernetes.io~empty-dir/secrets-init-bin\\\" to rootfs
\\\"/var/lib/docker/overlay2/d4827f88cc99549275789bcaf477f905fbc7e24847d1ae110e680fb2e759c064/merged\\\" at
\\\"/var/lib/docker/overlay2/d4827f88cc99549275789bcaf477f905fbc7e24847d1ae110e680fb2e759c064/merged/secrets-
init/bin\\\" caused \\\"not a directory\\\"\"": unknown:
Are you trying to mount a directory onto a file (or vice-versa)?
Check if the specified host path exists and is the expected type.
```

Kind regards,
Sergei

**Comment by sagikazarmark** [comment] 2021-04-21 10:40
It's probably caused by a change in `secrets-init`. Add `--image=doitintl/secrets-init:0.2.18` to your kube-secrets-init instance to roll back to an older version.

**Comment by sdevang** [comment] 2021-04-21 10:54
I can confirm that the issue is resolved with adding `--image=doitintl/secrets-init:0.2.12`in kube-secrets-init deployment.

@sagikazarmark @burningalchemist

**Comment by alexei-led** [comment] 2021-04-21 15:54
fixed

**Closed by alexei-led** 2021-04-21 15:54 UTC

**Comment by sagikazarmark** [comment] 2021-04-21 19:49
If anyone uses the helm chart I created: I added support for changing the [init container image tag](https://github.com/sagikazarmark/helm-charts/tree/master/charts/kube-secrets-init#init-container-image).

**Comment by onsails** [comment] 2021-12-30 18:19
I have the same problem with the latest `ghcr.io/doitintl/secrets-init:0.4.0` and 0.4.0 as well.
